version: "3.9"  # optional since v1.27.0
services:
  backend:
    image: "saucegenji/springboot-react:latest"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev